# User dédié pour le service Tomcat
group: "tomcat2"
user: "tomcat2"
home: "/opt/{{ user }}"
shell: /bin/false

extract_path: "{{ home }}"

# Tomcat service
service_name: tomcat
service_file: "/etc/systemd/system/{{ service_name }}.service"
java_home: "/usr/lib/jvm/java-17-openjdk-amd64"

# variable du fichier server.xml
shutdown_port: 8005
http_port: 8080

# application .war file 
war_file_src: "myapp1.war"
war_file_dest: "{{ home }}/webapps/{{ war_file_src }}"