ansible_connection: local

# User dédié pour le service Tomcat
group: "tomcat"
user: "tomcat"
home: "/opt/{{ user }}"
shell: /bin/false

extract_path: "{{ home }}"
# Tomcat service
service_name: "tomcat"
service_file: "/etc/systemd/system/{{ service_name }}.service"
java_home: "/usr/lib/jvm/default-java"

# variable du fichier server.xml
shutdown_port: 8020
http_port: 8042

# application .war file 
war_file_src: "myapp2.war"
war_file_dest: "{{ home }}/webapps/{{ war_file_src }}"