---
- name: Installation de Java sur Debian
  package:
    name: "{{ java_package }}"
    state: present
    update_cache: yes
  tags: tomcat_installation, java, package

- name: Création du groupe Tomcat
  group:
    name: "{{ tomcat_group }}"
  tags: tomcat_installation, group, user

- name: Création de l'utilisateur Tomcat
  user:
    name: "{{ user_linux.user }}"
    home: "{{ user_linux.user }}"
    create_home: yes
    shell: false
    group: "{{ user_linux.group }}"
  tags: tomcat_installation, user

- name: Télécharger l'archive Tomcat
  get_url:
    url: "{{ tomcat_package.archive_url }}"
    dest: "/tmp/"
    mode: '0644'
  tags: tomcat_installation, tomcat

- name: Décompresser l'archive Tomcat
  unarchive:
    src: "/tmp/{{ tomcat_package.archive }}"
    dest: "{{ tomcat_package.extract_path }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
  tags: tomcat_installation, tomcat

- name: rendre l'utilisateur propriétaire du répertoire tomcat
  file:
    path: "{{ user_linux.home }}"
    state: directory
    recurse: yes
    owner: "{{ user_linux.user }}"
    group: "{{ user_linux.group }}"
  tags: tomcat_installation

- name: Rendre exécutables les scripts du dossier bin
  file:
    path: "{{ item }}"
    mode: '0755'
  loop: "{{ bin_scripts }}"
  tags: tomcat_installation, executable

- name: Création du fichier service tomcat
  template:
    src: templates/tomcat.service.j2
    dest: "{{ service_file }}"
  tags: service, create

- name: Recharger les fichiers systemd
  systemd:
    daemon_reload: yes
  tags: service, reload 

- name: Démarrer le service Tomcat
  systemd:
    name: "{{ service_name }}"
    state: restarted
  tags: service, restart

- name: Activer Tomcat au démarrage
  systemd:
    name: "{{ tomcat_service_name }}"
    enabled: yes
  tags: service, enable

- name: Configuration de server.xml
  template:
    src: templates/server.xml.j2
    dest: "{{ tomcat_home }}/conf/server.xml"
  tags: config, server

- name: Supprimer l'ancien WAR s'il existe
  file:
    path: "{{ war_file_dest }}"
    state: absent
  tags: deploy, clean

- name: déployer l'application
  copy:
    src: "files/{{ war_file_src }}"
    dest: "{{ war_file_dest }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0644'
  tags: deploy, war
    
